---
apiVersion: v1
kind: ConfigMap
metadata:
  name: boop-config
data:
  LOG_LEVEL: "info"
  PORT: "8080"
  JOB_IMAGE: "ghcr.io/qubitquilt/boop-runner@sha256:1e77a54d634bfe0deba41fcffd64ed6d7e0bc80ba9633928c6196a75d7769cd0"
  TARGET_NAMESPACE: "dev-tools"
