---
apiVersion: v1
kind: ConfigMap
metadata:
  name: boop-config
data:
  LOG_LEVEL: "info"
  PORT: "8080"
  JOB_IMAGE: "ghcr.io/qubitquilt/boop-runner@sha256:270bb9f48214976d1aeaefdca590cbdb33a0a3881daa7255bf9f06781dab5486"
  TARGET_NAMESPACE: "dev-tools"
