---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boop-receiver
imagePullSecrets:
  - name: ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boop-job
imagePullSecrets:
  - name: ghcr-pull
